import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fightPose} from './src/fight-plan.js';
import {frameAt} from './src/scene-art.js';
const manifest=JSON.parse(readFileSync(new URL('./public/assets/scenes/manifest.json',import.meta.url)));
const pose=t=>fightPose(manifest,t);
assert.equal(pose(3999).beat,'arrival');assert.equal(pose(4000).beat,'challenge');
assert.equal(pose(8000).beat,'kestrel-beam');assert.equal(pose(11000).beat,'dragon-fire');
assert.equal(pose(15000).beat,'hit');assert.equal(pose(18000).beat,'retreat');
assert.equal(pose(14999).beam.released,false);assert.equal(pose(14999).impact,null);
const hit=pose(15000);assert.equal(hit.beam.released,true);assert.equal(hit.dragon.frame,0);
assert.equal(hit.kestrel.y,185);assert.deepEqual([hit.impact.x,hit.impact.y,hit.impact.size],[1030,315,144]);
assert.deepEqual(pose(15499).impact.x,hit.impact.x);assert.equal(pose(15500).impact,null);
assert.equal(pose(11359).fire.stream,false);assert.equal(pose(11360).fire.stream,true);
assert.equal(pose(11880).fire.stream,false);assert.equal(pose(12100).fire,null);
assert.equal(frameAt(manifest.assets['dragon-hit'],99999),5,'one-shots hold their last native cel');
assert.equal(frameAt(manifest.assets['fish-wait'],8000),0,'fishing keeps its native eight-second loop');
assert.equal(pose(23999).beat,'retreat');assert(pose(23999).dragon.x>1319);
console.log('PASS: fight beat boundaries, causal counter-shot, world-locked impact, fire release and native timing');
